# Generated by Django 3.0.4 on 2020-05-26 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemChangeLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Item Changelog',
                'verbose_name_plural': 'Item Changelog',
                'db_table': 'changelog_item',
            },
        ),
        migrations.CreateModel(
            name='ListChangeLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'List Changelog',
                'verbose_name_plural': 'List Changelog',
                'db_table': 'changelog_list',
            },
        ),
        migrations.CreateModel(
            name='ListReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=127)),
                ('remarks', models.CharField(blank=True, default='', max_length=255)),
                ('timestampReceived', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'List Report',
                'verbose_name_plural': 'List Reports',
                'db_table': 'list_report',
            },
        ),
        migrations.CreateModel(
            name='UserReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=127)),
                ('remarks', models.CharField(blank=True, default='', max_length=255)),
                ('timestampReceived', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User Report',
                'verbose_name_plural': 'User Reports',
                'db_table': 'user_report',
            },
        ),
    ]
