# Generated by Django 3.0.4 on 2020-05-26 22:44

from django.db import migrations, models
import framework.utils.cornflakes.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collaborator',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('timestampCreated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Collaborator',
                'verbose_name_plural': 'Collaborators',
                'db_table': 'list_collaborator',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', framework.utils.cornflakes.fields.ShadedIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=127, verbose_name='Name')),
                ('comment', models.CharField(blank=True, default='', max_length=255, verbose_name='Comment')),
                ('url', models.CharField(blank=True, default='', max_length=255, verbose_name='URL')),
                ('timestampCreated', models.DateTimeField(auto_now=True)),
                ('timestampLastEdited', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
                'db_table': 'item',
            },
        ),
    ]
