# Generated by Django 3.0.4 on 2020-05-26 22:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taxonomy', '0001_initial'),
        ('poll', '0001_initial'),
        ('list', '0002_itemmedia_list_listvote_position_rating_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='voter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rating',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='list.Item'),
        ),
        migrations.AddField(
            model_name='rating',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='listvote',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='list.Item'),
        ),
        migrations.AddField(
            model_name='listvote',
            name='list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='list.List'),
        ),
        migrations.AddField(
            model_name='listvote',
            name='voter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='list',
            name='curator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Curator'),
        ),
        migrations.AddField(
            model_name='list',
            name='firstItem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_item', to='list.Item'),
        ),
        migrations.AddField(
            model_name='list',
            name='hashTags',
            field=models.ManyToManyField(blank=True, db_table='list_tag', to='taxonomy.Tag'),
        ),
        migrations.AddField(
            model_name='list',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='taxonomy.Topic'),
        ),
        migrations.AddField(
            model_name='itemmedia',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='list.Item'),
        ),
        migrations.AddField(
            model_name='item',
            name='contributor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_contributor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='item',
            name='correctOption',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='correct_option', to='poll.PollOption'),
        ),
        migrations.AddField(
            model_name='item',
            name='hashTags',
            field=models.ManyToManyField(blank=True, db_table='item_tag', to='taxonomy.Tag'),
        ),
        migrations.AddField(
            model_name='item',
            name='list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='list.List', verbose_name='List'),
        ),
        migrations.AddField(
            model_name='item',
            name='mentions',
            field=models.ManyToManyField(blank=True, db_table='item_mention', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='item',
            name='pollOptions',
            field=models.ManyToManyField(blank=True, db_table='item_poll_option', to='poll.PollOption'),
        ),
        migrations.AddField(
            model_name='item',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='list.Item', verbose_name='Source Item'),
        ),
        migrations.AddField(
            model_name='collaborator',
            name='list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='list.List'),
        ),
        migrations.AddField(
            model_name='collaborator',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('item', 'voter')},
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('item', 'reviewer')},
        ),
        migrations.AddField(
            model_name='position',
            name='list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='list.List'),
        ),
        migrations.AddField(
            model_name='position',
            name='next',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_item', to='list.Item'),
        ),
        migrations.AlterUniqueTogether(
            name='listvote',
            unique_together={('list', 'voter')},
        ),
        migrations.AddField(
            model_name='list',
            name='items',
            field=models.ManyToManyField(related_name='item_lists', through='list.Position', to='list.Item'),
        ),
        migrations.AlterUniqueTogether(
            name='itemmedia',
            unique_together={('media', 'item')},
        ),
        migrations.AlterUniqueTogether(
            name='collaborator',
            unique_together={('list', 'user')},
        ),
    ]
