# Generated by Django 3.0.4 on 2020-05-26 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curation', '0001_initial'),
        ('list', '0002_itemmedia_list_listvote_position_rating_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='featuredlist',
            name='list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='list.List'),
        ),
    ]
