# Generated by Django 3.0.4 on 2020-05-26 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('list', '0002_itemmedia_list_listvote_position_rating_vote'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowUserRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Follow User Request',
                'verbose_name_plural': 'Follow User Requests',
                'db_table': 'follow_user_request',
            },
        ),
        migrations.CreateModel(
            name='ListEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('positionRequested', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'List Entry',
                'verbose_name_plural': 'List Entries',
                'db_table': 'list_entry',
            },
        ),
        migrations.CreateModel(
            name='ListRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, default='', max_length=255)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('list', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requested_list', to='list.List')),
            ],
            options={
                'verbose_name': 'List Request',
                'verbose_name_plural': 'List Requests',
                'db_table': 'list_request',
            },
        ),
    ]
