# Generated by Django 3.0.4 on 2020-05-26 22:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('list', '0003_auto_20200526_2244'),
        ('user', '0001_initial'),
        ('request', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listrequest',
            name='requester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_requester', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='listrequest',
            name='respondent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_request_respondent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='listentry',
            name='approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='list_entry_approver', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='listentry',
            name='contributor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_entry_contributor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='listentry',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='list.Item'),
        ),
        migrations.AddField(
            model_name='listentry',
            name='list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='list.List'),
        ),
        migrations.AddField(
            model_name='listentry',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='list.Position'),
        ),
        migrations.AddField(
            model_name='followuserrequest',
            name='requester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_requester', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='followuserrequest',
            name='respondent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_respondent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='followuserrequest',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.UserSubscription'),
        ),
    ]
