# Generated by Django 3.0.4 on 2020-05-26 22:44

from django.db import migrations, models
import framework.utils.cornflakes.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', framework.utils.cornflakes.fields.ShadedIDField(primary_key=True, serialize=False)),
                ('url', models.URLField(unique=True)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.CharField(blank=True, default='', max_length=511)),
                ('image', models.CharField(blank=True, default='', max_length=255)),
                ('retrievedTimestamp', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Link',
                'verbose_name_plural': 'Links',
            },
        ),
    ]
