# Generated by Django 3.0.4 on 2020-05-26 22:44

from django.db import migrations, models
import django.db.models.deletion
import framework.utils.cornflakes.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('list', '0002_itemmedia_list_listvote_position_rating_vote'),
    ]

    operations = [
        migrations.CreateModel(
            name='PollOption',
            fields=[
                ('id', framework.utils.cornflakes.fields.ShadedIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Poll Option',
                'verbose_name_plural': 'Poll Options',
                'db_table': 'poll_option',
            },
        ),
        migrations.CreateModel(
            name='UserPollChoice',
            fields=[
                ('id', framework.utils.cornflakes.fields.ShadedIDField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='poll.PollOption')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='list.Item')),
            ],
            options={
                'verbose_name': 'User Poll Choice',
                'verbose_name_plural': 'User Poll Choices',
                'db_table': 'user_poll_choice',
            },
        ),
    ]
