# Generated by Django 3.0.4 on 2020-05-26 22:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('media', '0002_media_uploader'),
        ('poll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpollchoice',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='polloption',
            name='media',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='media.Media'),
        ),
        migrations.AlterUniqueTogether(
            name='userpollchoice',
            unique_together={('user', 'item')},
        ),
    ]
